<?php
/***************************************************************
 * Extension Manager/Repository config file for ext: "kdstotop"
 *
 * Auto generated by Extension Builder 2017-09-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Kds-Totop',
    'description' => 'Insert a scroll to top plugin',
    'category' => 'plugin',
    'author' => 'Oliver Kurth',
    'author_email' => 'info@kds-kassel.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '11.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '11.0.0-11.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
